# Generated by Django 5.0.3 on 2024-11-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(max_length=24)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('pred_date', models.DateField()),
                ('place1', models.CharField(max_length=6)),
                ('place2', models.CharField(max_length=6)),
                ('place3', models.CharField(max_length=6)),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('rain_rate', models.IntegerField()),
                ('weather', models.CharField(max_length=6)),
                ('confidence', models.CharField(blank=True, max_length=6, null=True)),
                ('weather_clear', models.FloatField()),
                ('weather_sunny', models.FloatField()),
                ('weather_cloudy', models.FloatField()),
                ('weather_rainy', models.FloatField()),
                ('weather_snow', models.FloatField()),
                ('weather_blizzard', models.FloatField()),
                ('weather_typhoon', models.FloatField()),
                ('cloud_duration', models.FloatField()),
                ('rain_duration', models.FloatField()),
                ('sunny_duration', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
